version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: django
    versions:
    - ">=3"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: python
    versions:
    # Django 3.2 LTS only supports Python up to 3.10
    - ">3.10"
  commit-message:
    prefix: chore
    include: scope
