version: "3"
services:
  db:
    image: postgres:12.2-alpine@sha256:9ea72265275674225b1eaa2ae897dd244028af4ee7ef6e4e89fe474938e0992e
    environment:
      - POSTGRES_USER=emeis
      # following option is a must to configure on production system:
      # https://hub.docker.com/_/postgres
      # - POSTGRES_PASSWORD=
    volumes:
      - dbdata:/var/lib/postgresql/data
  emeis:
    image: ghcr.io/projectcaluma/emeis:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      # following options are a must to configure on production system:
      # https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-SECRET_KEY
      # - SECRET_KEY=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts
      # - ALLOWED_HOSTS=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#password
      # same as postgres password above
      # - DATABASE_PASSWORD=

volumes:
  dbdata:
